### ISSUE TITLE
Reply on unknown commands

### ISSUE THREAD

**Issue by bertptrs** [channable/hoff#102]
Sometimes the user issues a command and Hoff will not know what to respond. For example, if you accidentally add a second space between the mention and the command, Hoff will silently ignore it. This is hard to spot. Could we make Hoff reply when it gets tagged but no action is taken?

**Comment by RileyApeldoorn** [comment]
@bertptrs For the specific example you mentioned, it might also be more user-friendly to accept one or more spaces between the mention and the command instead of just one.

**Comment by bertptrs** [comment]
Indeed it would. However, it is also very easy to tell Hoff to mergre or other creative typos, so I think we should tackle the general case (and maybe make the specific cases we can unambiguously fix nicer).

**Comment by RileyApeldoorn** [comment]
Of course, for those cases there should still be an error message, but in the specific case of extra whitespace, being lenient seems like good UX to me. Maybe we can apply a sort of "fixup" function to the body to trim whitespace, potentially supplied in the configuration?

Though it's probably better to do that in a separate issue as an improvement in addition to the current error message.
