### ISSUE TITLE
Make Hoff post the URL to the CI run when merging

### ISSUE THREAD

**Issue by maartenberg** [channable/hoff#109]
Currently when merging a PR Hoff will comment "Rebased as `abcd123`, waiting for CI …" once it has rebased the branch to be merged.
While this is happening the original branch will be untouched, if the tests pass on that branch it will seem as if the tests for the branch to be merged are done already. While this is happening Hoff is actually waiting for a different CI run to complete, which can currently only be reached by manually navigating to the rebased commit's tests.

It would be a better experience if Hoff would post the CI link to the PR that is being merged once this link is known.

Todo:
1. Wait for webhook confirming that a CI run has started
2. Post comment on PR that CI has started with this link

**Comment by ruuda** [comment]
I thought there was an issue for this already, but now I see I only mentioned it as a drive-by in https://github.com/channable/hoff/issues/44 and https://github.com/channable/hoff/issues/26. #26 is about displaying it in the webinterface, but it would make sense to me to also add it as a link in comments. [According to my past self](https://github.com/channable/hoff/issues/26#issuecomment-578730224) the url of the CI run is already there, but I never verified this.
