### ISSUE TITLE
Make CI red when build fails

### ISSUE THREAD

**Issue by rudymatela** [channable/hoff#119]
Currently (Jun 2022) Hoff, whenever the `nix-build` step fails, the CI does not detect it and we are left with a green build :heavy_check_mark: even though the build was supposed to be red :x:.

Here is an example:

* [Green build](https://channable.semaphoreci.com/workflows/c053ce0e-880c-4051-8360-2d3bb5bcb522?pipeline_id=2a9232e6-01e7-49fe-a86d-71c3c07a9872):

    ![1](https://user-images.githubusercontent.com/3999598/173055472-fedc4a2a-f388-40e9-9aa1-3ac5b42d1705.png)

* [All steps green](https://channable.semaphoreci.com/jobs/72477fc0-1a72-4f13-b220-fa53d203f1db):

    ![2](https://user-images.githubusercontent.com/3999598/173055538-f776bfa0-a1c2-4148-83ab-5a579c10ec41.png)

    Nice!

* [Actual result of the nix-build step](https://channable.semaphoreci.com/jobs/72477fc0-1a72-4f13-b220-fa53d203f1db#L2005-L2009):

    ![3](https://user-images.githubusercontent.com/3999598/173055830-2533af83-4ef5-4509-bc00-614465049625.png)

    Ohno!  :scream: 

Here's the failing command and output section:

```
$ nix-build --no-out-link release.nix | cachix push channable-public
...
[11 of 12] Compiling WebInterface     ( src/WebInterface.hs, dist/build/WebInterface.p_o ) 00:43
[12 of 12] Compiling Server           ( src/Server.hs, dist/build/Server.p_o ) 00:45
dist/build/libHShoff-0.25.2-9YPwmF3FCRkEo14kDrjgdt-ghc8.10.4.a: hPutBuf: resource exhausted (No space left on device) 00:45
error: writing to file: No space left on device 00:45
Nothing to push. 00:45 
```

Semaphore fails to detect this as although `nix-build` fails, `cachix` succeeds.  The error code of a pipe is (normally) the error code of the last command.  So we should try to break down the commands into two.  Something like this:

```bash
nix-build --no-out-link release.nix > something

cat something | cachix push channable-public
```

## Issue present since 19 April 2022

The CI build was failing all along for two previous versions:

* [v0.25.1](https://channable.semaphoreci.com/jobs/0d0867ad-d8a8-4f39-85a5-b1f47f23b051#L899-L905)
* [v0.25.0](https://channable.semaphoreci.com/jobs/e7a14e89-635d-4e6a-81b0-cad8992eb4ca#L897-L901)

The issue has been here since 19 April 2022 after [this merge](https://channable.semaphoreci.com/jobs/8139392c-cfef-41d5-9a97-f1fd4056f4c4#L897-L901) with hash c4c2e38353046a9526e4ffd5390e6b38b554cbcf PR #105.

The CI build was still okay on [v0.24.0](https://channable.semaphoreci.com/jobs/c12e8870-4fc0-48f2-a058-64f077a45d06)

**Comment by ruuda** [comment]
> Semaphore fails to detect this as although nix-build fails, cachix succeeds. The error code of a pipe is (normally) the error code of the last command.

You can also `set -o pipefail` to prevent errors from being masked.
