### ISSUE TITLE
Improve development instructions

### ISSUE THREAD

**Issue by rudymatela** [channable/hoff#125]
Hoff currently has an [installation guide](https://github.com/channable/hoff/blob/master/doc/installing.md) pointed out by the [README](https://github.com/channable/hoff#readme).  However, the "development" instructions are a bit lacking, such as how to use `tools/send-webhook.py` and a quick set-up guide for a development environment with Hoff running locally.  Perhaps we should create one?

I am marking this as a prerequisite to #77.

**Comment by rudymatela** [comment]
Here is my currenct, `config.json` file:

```json
{
  "projects": [{
    "owner": "channable",
    "repository": "git-sandbox",
    "branch": "master",
    "testBranch": "testing",
    "checkout": "./run/checkouts/your-username/your-repo",
    "stateFile": "./run/hoff/state/your-username/your-repo.json"
  }],
  "secret": "run 'head --bytes 32 /dev/urandom | base64' and paste output here",
  "accessToken": "paste a personal access token for a bot user here",
  "port": 1979,
  "tls": null,
  "user": {
    "name": "CI Bot",
    "email": "cibot@example.com",
    "sshConfigFile": "/etc/hoff/ssh_config"
  },
  "mergeWindowExemption": ["hoffbot"],
  "trigger": {
    "commentPrefix": "@hoffbot"
  }
}
```

When I run `nix run -c stack exec hoff config.json` I get the following error:

```bash
$ nix run -c stack exec hoff config.json
Config file: config.json
Read-only: False
File './run/hoff/state/your-username/your-repo.json' not found, starting with an empty state.
[Info] executing git clone --config transfer.fsckObjects=true --config user.name=CI Bot --config user.email=cibot@example.com git@github.com:channable/git-sandbox.git ./run/checkouts/your-username/your-repo
Listening for webhooks on port 1979.
[Warn] git clone failed with code ExitFailure 128: Cloning into './run/checkouts/your-username/your-repo'...
ssh -F /etc/hoff/ssh_config: ssh: command not found
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Whoa!  `ssh` not found?  Well:

```bash
$ ssh -F /etc/hoff/ssh_config
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]

$ nix run -c ssh -F /etc/hoff/ssh_config
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
```

Whoa?!  :thinking:

@RileyApeldoorn, @ReinierMaas, @tiesjan or @alter2000, did you face a similar problem while trying to run Hoff?  (I'm tagging all of you since I know you all recently worked on this project.)

**Comment by rudymatela** [comment]
It seems I needed `--no-nix-pure` as an argument to `stack exec`:

```bash
nix run -c stack exec hoff config.json --no-nix-pure
```

This is something I should add in the build instructions.

Thanks to @xrvdg and @joris-burgers for providing the solution and details for this.

**Comment by rudymatela** [comment]
Here is an updated `config.json` to use in development:

```json
{
  "projects": [{
    "owner": "channable",
    "repository": "git-sandbox",
    "branch": "master",
    "testBranch": "testing",
    "checkout": "./run/checkouts/git-sandbox",
    "stateFile": "./run/hoff/state/git-sandbox.json"
  }],
  "secret": "0NOTREALLYASECRET0",
  "accessToken": "0NOTREALLYATOKEN0",
  "port": 1979,
  "tls": null,
  "user": {
    "name": "CI Bot",
    "email": "cibot@example.com",
    "sshConfigFile": "/dev/null"
  },
  "mergeWindowExemption": ["hoffbot"],
  "trigger": {
    "commentPrefix": "@hoffbot"
  }
}
```

@alter2000 You may be interested in this.

**Comment by alter2000** [comment]
Thank you! I'm going to add actual tests without running the executable but I'll give this a go.

**Comment by rudymatela** [comment]
It seems that the [send-webhook.py](/tools/send-webhook.py) is not working properly:

```bash
 ./tools/send-webhook.py issue_comment created 31337 someone "@hoffbot merge"
400: missing or malformed X-Hub-Signature header
```

**Comment by rudymatela** [comment]
The last commit is from 2016!  So maybe it is stale?

**Comment by rudymatela** [comment]
> Yep ... the last change to that script definitely predates the implementation of hmac verification by 52 commits ... Maybe there should be a CLI flag to disable hmac verification for debugging purposes. Or maybe the script should just be deleted as it is no longer useful.

Hey @ruuda, thanks for the reply.  :smile:

I thought about disabling HMAC temporarily for my tests (by commenting some code locally) but I wanted to make a request as close as possible to GitHub so I started building a new script.  I think it was worth it: in the process of building the script I discovered a potential bug in HMAC calculation: #127.
