### ISSUE TITLE
Hoff fails for GitHub payloads containing line breaks `\n`

### ISSUE THREAD

**Issue by rudymatela** [channable/hoff#127]
We seem to be relying on the fact that [GitHub webhook payloads](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-17) are sent without any line breaks for Hoff to work corretly.

If GitHub changes the format to a (valid) JSON that includes line breaks, Hoff will stop working as it will reject all GH requests with: `signature does not match, is the secret set up properly?`.  This might never happen, this might happen in the upcoming week.  We are counting on luck here.  :game_die:

Here is how to reproduce the bug (using part of the [new WIP dev instructions](https://github.com/channable/hoff/pull/126)).  Consider the following script that simulates a GH webhook call:

```bash
#!/bin/bash
  
cat >webhook-data.json <<DATA
{ 
    "action": "whatever"
} 
DATA
  
secret=`cat config.json  | grep secret | sed 's/.* "//;s/".*//'`
signature1=`cat webhook-data.json | openssl dgst -sha1 -hmac "$secret" | sed 's/^.* //'`
signature256=`cat webhook-data.json | openssl dgst -sha256 -hmac "$secret" | sed 's/^.* //'`
      
curl \  
    -XPOST \ 
    -w "\n\n%{http_code}\n" \
    -H "X-GitHub-Event: issue_comment" \
    -H "X-Hub-Signature: sha1=$signature1" \
    -H "X-Hub-Signature-256: sha256=$signature256" \
    http://localhost:1979/hook/github \
    -d @webhook-data.json
```

Running it yields:

```bash
$ ./tools/send-webhook
signature does not match, is the secret set up properly?
```

If we instead replace the contents of `webhook-data.json` by something without linebreaks in the above script:

```bash
echo -n '{"action": "whatever"}' >webhook-data.json
```

Running it yields what is expected:

```bash
$ ./tools/send-webhook
<h1>422 Unprocessable Entity</h1>jsonData - failed parse. Data was: {"action": "whatever"}. Error was: unexpected issue_comment action
```

The signature check passes and the request fails later as this is an invalid payload.

A mere line break at the end of file can trigger this issue!  The following also causes a failure:

```bash
echo '{"action": "whatever"}' >webhook-data.json
```

### Further proof

If we `traceShow` the message (`:: ByteString`) that arrives in [`isSignatureValid`](https://github.com/channable/hoff/blob/bcb3a134994ee16b19441ee6c62f1c290ac7f4e6/src/Server.hs#L62-L74):

```haskell
isSignatureValid :: Text -> Text -> ByteString -> Bool
isSignatureValid _ _ message | traceShow message False = undefined
isSignatureValid ...
```

we see that the line breaks are not there (though tabs and spaces are kept!):

```bash
"{    \"action\": \"created\"}"
```

This may come from a bug on [Scotty](https://hackage.haskell.org/package/scotty) itself.  Perhaps the function [`jsonData`](https://www.stackage.org/haddock/lts-19.13/scotty-0.12/Web-Scotty.html#t:ScottyM) strips out line breaks (though this is not confirmed).  We can submit a patch there, but in the meanwhile we could fix this on Hoff by running the signature check as early as possible.

### Further info

Even if GitHub promises to not send JSON with line breaks ever, I think we should fix this anyway: I spent almost an hour debugging why the HMAC checks for my custom payload was not working, only to discover that I should have ignored line breaks when computing it.

### History / Context

This was discovered while I was working on PR #126.

**Comment by fatho** [comment]
> This may come from a bug on [Scotty](https://hackage.haskell.org/package/scotty) itself. Perhaps the function [`jsonData`](https://www.stackage.org/haddock/lts-19.13/scotty-0.12/Web-Scotty.html#t:ScottyM) strips out line breaks (though this is not confirmed). We can submit a patch there, but in the meanwhile we could fix this on Hoff by running the signature check as early as possible.

The signature check already happens before the body is parsed as JSON: https://github.com/channable/hoff/blob/bcb3a134994ee16b19441ee6c62f1c290ac7f4e6/src/Server.hs#L100

I believe what you're actually running into is a mistake in how curl is invoked. `man curl` says about the `-d` option (short for `--data`):

> When --data is told to read from a file like that,  carriage  returns  and  newlines will  be stripped out.

What you actually want is `--data-binary`, which doesn't do any preprocessing:

```
       --data-binary <data>
              (HTTP) This posts data exactly as specified with no extra processing whatsoever.

              If  you  start the data with the letter @, the rest should be a filename.  Data is posted
              in a similar manner as -d, --data does, except that newlines  and  carriage  returns  are
              preserved and conversions are never done.

              Like -d, --data the default content-type sent to the server is application/x-www-form-ur‐
              lencoded. If you want the data to be treated as arbitrary binary data by the server  then
              set the content-type to octet-stream: -H "Content-Type: application/octet-stream".

              If  this  option  is used several times, the ones following the first will append data as
              described in -d, --data.
```

**Comment by rudymatela** [comment]
> I believe what you're actually running into is a mistake in how curl is invoked. `man curl` says about the `-d` option (short for `--data`):

That's embarrassing.  :grimacing:  Hehehe.  The problem was between the chair and the keyboard :facepalm:.

I am closing this as a non-issue now.  I will update #126 to use `--data-binary`.

Thanks for spotting this @fatho!
