### ISSUE TITLE
Duplicate "CI job" messages

### ISSUE THREAD

**Issue by rudymatela** [channable/hoff#147]
Hoff is sometimes leaving duplicate CI job messages, like so:

> Waiting on CI job: https://ci.example.com/123

(30 seconds later)

> Waiting on CI job: https://ci.example.com/456

(25 seconds later)

> Waiting on CI job: https://ci.example.com/123

**Comment by rudymatela** [comment]
I think this issue happens whenever Hoff's `testing/*` rebase is a fastforward into master (with just one commit).  So the following is an example situation on which this will happen:

1. a commit `1234abc` on `add-stuff` is created with a PR;
2. the `@hoffbot merge` command is issued;
3. Hoff is able to rebase `1234abc` with a fastforward, no new commit is created;
4. Hoff pushes `1234abc` to be the head of `testing/...`;
5. GitHub notifies:
    1. build of commit `1234abc` in branch `add-stuff` pending with URL `https://ci.example.com/123`
    2. build of commit `1234abc` in branch `testing/*` pending with URL `https://ci.example.com/456`
    3. build of commit `1234abc` in branch `add-stuff` pending with URL `https://ci.example.com/123`

Before posting a comment, Hoff simply checks if the build status is different than the previous, since in this case we are going back and forth between two branches but with the same commit, Hoff posts multiple comments.

This in fact happens because for the same commit on multiple branches, Semaphore and GitHub create separate builds!

This is the relevant code section that triggers the comments:

https://github.com/channable/hoff/blob/78cfbfb4ab3fa09b17503f6895044a06be5ada06/src/Logic.hs#L545-L558

Instead of simply checking `candidateSha == buildSha && newStatus /= oldStatus`, we also need to check that `candidateBranch == buildBranch` so we effectively ignore the builds for the same commit that happen in different branches.

This caveat has always been present, but it only became visible with #138 (v0.25.8) when we started reporting the URL for CI (#109).  All versions of Hoff so far merge to master when either `add-stuff` or `testing/*` build passes :heavy_check_mark: (given something similar to the above situation).  We did not use to get duplicate comments because Hoff stops handling the PR after merging, so it's only a real issue now.  (Before it was perhaps some unimportant "internal consistency" issue.)

**Comment by rudymatela** [comment]
This issue was originally reported by @FPtje and @bertptrs.  Thanks for reporting!  :-)

**Comment by rudymatela** [comment]
We could perhaps use the [branches array of the relevant GitHub webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#status) to populate the `buildBranch` variable.

I looked at the logs, and we currently do not record this, so I am unsure whether this will only list the "official' branch of the build or other builds.  I'll have to check the results of the real GitHub webhook with a local test or after a deploy.  I think I will "optimistically" assume that it will only include the official branch in the list for my current implementation.

**Comment by rudymatela** [comment]
This new version has been deployed.

Here's how I tested it afterwards (on a project that takes 60 seconds to build):

* create branch `break-build`;
* push it;
* quickly create a PR and "@hoffbot merge";
* push another branch pointing to the same commit as well.

After performing the above test, the issue is still there.

It seems GitHub does not provide a way to detect the "canonical" build through the Git webhook, as all will point to the branch in the list.  I'll have to rethink this.

**Comment by rudymatela** [comment]
From my tests: GitHub does limit the number of listed branches to 10... and it seems to do so alphabetically.  This may make us lose build statuses in extreme cases.

**Comment by rudymatela** [comment]
I reverted the merge of PR #148 in faf04c96486cb9dc30b6f133f6574ceab3401955.

The reasons listed in the commit message are copied here:

> The changes in PR https://github.com/channable/hoff/pull/148 did not fix what they were intended to fix (https://github.com/channable/hoff/issues/147).  At the same time they introduced a bug in extreme cases: when more than 10 branches point to the same commit, we may loose a build status change notification on the right branch.
>
> We could maintain these changes partially to include logging what branches GitHub lists, but I don't think the maintaining costs justify this.

**Comment by rudymatela** [comment]
... from a discussion with @fatho on mattermost:

> I am starting to think that GitHub may send BuildPending statuses periodically
> (Maybe when a build step completes)

That's why we receive https://ci.example.com/123 twice in the example showed in the PR description and in a couple of PRs that link to hhere.

**Comment by rudymatela** [comment]
We can keep observing if this happens too frequently over the next week and re-evaluate whether it is worth mitigating in [some other way](https://github.com/channable/hoff/pull/152#issuecomment-1206349085).

**Comment by rudymatela** [comment]
We just had a PR where the CI job message appeared six times.  Perhaps this issue ought to be reopened after all...  We can just keep the list of URLs that arrived so far so that the number of reported URLs is limited to two.

Thanks to @ReinierMaas for bringing this to attention.

**Comment by rudymatela** [comment]
> Thanks to @ReinierMaas for bringing this to attention.

... and to @alex-mckenna as well.  (I just saw the separate message.)

**Comment by alex-mckenna** [comment]
Infra Green is always watching :eyes:
