### ISSUE TITLE
Post exact rebase command in failed rebase message

### ISSUE THREAD

**Issue by ruuda** [channable/hoff#15]
When a rebase fails, the bot leaves a comment asking to rebase manually. It would be nice if it included the exact command to run, or maybe the last commit after which the rebase stopped. That would make it clearer what action to take; I just rebased but forgot the interactive part to apply fixups.

**Comment by fatho** [comment]
> I just rebased but forgot the interactive part to apply fixups.

In that case the bot could still autosquash all fixups if there are any, even if the branch is already on top of master.

**Comment by ruuda** [comment]
> In that case the bot could still autosquash all fixups if there are any, even if the branch is already on top of master.

It does, and that is what failed. I just forgot to include `--interactive` myself locally.
