### ISSUE TITLE
Rethink our command parsing code

### ISSUE THREAD

**Issue by Riscky** [channable/hoff#212]
Currently, our command parsing code is somewhat ad-hoc.
Basically, we build up a list of strings, compare it to the entered command, and use the first match.
This works good enough for now, but we're adding more and more commands, which also require us to give back better feedback.

For example, we have recently introduced the `merge and deploy to <environment>` command (https://github.com/channable/hoff/pull/210).
Let's say we configure a project with two environments, `staging` and `production`.
If a user tags the bot with `merge and deploy to production`, Hoff will set the `Deploy-Environment: production` marker.
If a user tags the bot (incorrectly) with `merge and deploy to productie`, Hoff will instead of throwing an error, match against the `merge and deploy` command, and deploy to the default environment (which probably is staging).
This leads to unexpected results.

Instead of our current, ad-hoc, longest string match 'parser', we could (should?) use an actual parsing library, so we can tokenize the command, and give back useful errors in cases like the example above.
Instead of accepting `merge and deploy to productie` as a `merge and deploy` command, we could parse the `to <environment>` string as tokens, realize `productie` is not a valid environment, and show feedback accordingly.
Similarly, we can parse `and <action>` and `on <day>` and give useful feedback if an unknown action or day is put in, instead of silently ignoring it and falling back to the next match.

CC @HugoPeters1024

**Comment by HugoPeters1024** [comment]
I agree that this approach is overkill right now, but if more commands are added then it would become a viable option. I think this might be a good onboarding issue as well.

**Comment by robbert-vdh** [comment]
I'm looking into this now. Any opinions on how permissive the parser should be? If the command has to be on its own line  and everything until the end of the line is considered to be part of the command then that would avoid all situations where a single-line command would be interpreted incorrectly. In our case allowing the command to be any part of a that's delimited by the comment prefix and either a line feed, end of file, or a punctuation character would allow it to be sentence, (e.g. `Okay, then let's merge this thing @bottname merge.`), though allowing this in the middle of a paragraph would complicate things again if we ever add commands that take arbitrary string arguments. Any preferences here?

1) Require `@botname <command>` to be on its own line.
2) Allow `@botname <command>` to start at any point in a line, and allow it to be followed by one or more punctuation characters or spaces. Bit more flexible, commands that end with punctuation are ambiguous  (e.g. `merge!`)..
2) Allow `@botname <command>` to start at any point in a line and terminate the command by a punctuation character or the end of the line. Even more flexible, but it will cause ambiguity problems if commands ever contain arbitrary text.

**Comment by fatho** [comment]
How about 1.5: Start at `@botname` (since that's unambiguous) and parse from there until the end of the line ?
That then still allows easily flowing comments as:

> Flaky, test. Try again <span>@</span>botname merge

but prevents potentially ambiguous situations as

> <span>@</span>botname merge again due to flaky tests

that could conflict with future extensions of the command syntax.

**Comment by robbert-vdh** [comment]
Yeah with "noise" characters that's (2). Probably best to have a smaller subset of allowed characters there (i.e. `,.!?` + whitespace). The [`isPunctuation`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Char.html#v:isPunctuation) predicate includes a lot of other things like dashes and quotes. Starting the command in the middle of a sentence would always be fine but it's probably a bit confusing if you then can't end the sentence with a period.

**Comment by Riscky** [comment]
Making these situations parsing failures seems like the way to go indeed :+1:
