### ISSUE TITLE
CI Job comment link broken for certain commands

### ISSUE THREAD

**Issue by DanielNoord** [channable/hoff#227]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/0c952bf2-aacb-46b4-b15d-a4a654b45c52?pipeline_id=c34b0182-71ad-4711-adcb-ef33c4588f5f) started.

------------------------------------------------------------------------------

This is what Hoff posted on https://github.com/channable/requestmachine/pull/29184#issuecomment-1584074637. 
The only way I could get the link to work again was by removing the ignore mark.

**Comment by robbert-vdh** [comment]
Seems like GitHub's Markdown parser juts doesn't parse markdown if it's on the same line as an HTML comment. Probably a bug in their markdown parser, since it doesn't do that for other HTML tags. Thanks for bringing this to my attention! I'll add a line feed right away.
