### ISSUE TITLE
Allow jumping the merge train

### ISSUE THREAD

**Issue by bertptrs** [channable/hoff#259]
Sometimes, a fix needs to go out now, and waiting orderly in the queue isn't the best thing to do. It can make sense to reduce throughput of the overall merge train by letting a single commit

I propose we add a `NOW` or similarly dramatic suffix to all commands that cause a merge (and potentially a tag/deploy) that allows a PR to become the head of the merge train.

This invalidates any progress made on building the existing merge train, but I believe that's an acceptable trade-off for incidental use.

CC @rkrzr

Tangentially related to #253 which also tries to address this; I think we need both.

**Comment by Riscky** [comment]
> and potentially a tag/deploy

We should also add a field in the commit message to convey this information to deployment software, like we did with `Auto-deploy` for example (perhaps `Priority`?).
