### ISSUE TITLE
Display the current build status from CI in the Hoff dashboard

### ISSUE THREAD

**Issue by rkrzr** [channable/hoff#26]
It would be nice to have a link to the build on the `testing` branch.
On GH you only see the reference to Semaphore on the branch of that PR, but that is the status before the branch was rebased on `testing`.
This is slightly confusing, if you are not aware of that.

We could add this link in the Hoff dashboard , then one could easily access it.

**Comment by ruuda** [comment]
I thought that the commit status API would include a "more information" link somewhere in the payload, but at least [in the example that GitHub provides](https://github.com/channable/hoff/blob/master/tests/data/status-payload.json), it is not there. We should investigate if it is possible to get the link somehow.

**Comment by ruuda** [comment]
Actually, the url of the build *is* included in the webhook, and we already parse it:

https://github.com/channable/hoff/blob/8e22417cc4165edee487bfc67118b513aa387979/src/Github.hs#L82

We can add that to the pull request state and display it in the webinterface. We can also use this to turn the “The build failed.” comment into a link, as proposed in #44.
