### ISSUE TITLE
Make branch deletion configurable

### ISSUE THREAD

**Issue by fatho** [channable/hoff#32]
Hoff deletes the branch of the PR when merging it. This causes problems when there was another PR that used that branch as a base. It will be closed by github in that case.

Either Hoff shouldn't delete the branch in that case, or, maybe even easier, hoff could just not delete branches in general and instead rely on the github auto-deletion feature for merged branches.
That feature already correctly handles branches that are used as bases for other PRs.

**Comment by pawelulita** [comment]
Also, as the base branch doesn't exist any more, GH won't allow reopening the PR.

**Comment by ruuda** [comment]
We can probably just delete all the code that deals with deleting branches, now that GitHub has auto-deletion there is not much added value for Hoff to do it.
