### ISSUE TITLE
Changes to pull request titles are not picked up

### ISSUE THREAD

**Issue by ruuda** [channable/hoff#34]
If you change the title of a pull request, Hoff will not register the new title. I’m not sure which webhook gets delivered when the pull request title changes, but we would need to listen for it, and update the title in the internal state.

**Comment by ruuda** [comment]
This has become more important after https://github.com/channable/hoff/pull/67.

**Comment by fatho** [comment]
Should've been fixed by https://github.com/channable/hoff/pull/88
