### ISSUE TITLE
Can’t request merge directly from review comment

### ISSUE THREAD

**Issue by rightfold** [channable/hoff#47]
Hoff seems to ignore this comment:

![image](https://user-images.githubusercontent.com/5132125/74016858-6b73e900-4993-11ea-91ae-1b12f3e90c9c.png)

Perhaps it is a different kind of comment.
I created the comment using this form from the review screen:

![image](https://user-images.githubusercontent.com/5132125/74016889-821a4000-4993-11ea-8a5f-ad1b37b9016c.png)

**Comment by ruuda** [comment]
Yes, these are different things:

* The one we listen for is [`IssueCommentEvent`](https://developer.github.com/v3/activity/events/types/#issuecommentevent)
* I *think* review is [`PullRequestReviewEvent`](https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent), but it might be the `PullRequestReviewCommentEvent`.

**Comment by duijf** [comment]
https://github.com/channable/hoff/pull/57/ was accidentally linked to this PR, but should have been linked to https://github.com/channable/hoff/issues/55

This one isn't done yet
