### ISSUE TITLE
Leave a comment when the integration candidate is closed

### ISSUE THREAD

**Issue by ruuda** [channable/hoff#55]
## Summary

When the integration candidate pull request is closed, we delete the pull request from the state and clear the integration candidate, and [`proceedUntilFixedPoint`](https://github.com/channable/hoff/blob/af1069558d5162e9ff7596f13f30ba5aeeff6921/src/Logic.hs#L477-L485) will find the next thing to do, and carry on. We never give feedback on the closed pull request that we will no longer try to integrate it.

@ReinierMaas suggested we can leave a comment on close, to clarify that Hoff will abandon the pull request.

## Implementation pointers

A close event is handled here: https://github.com/channable/hoff/blob/af1069558d5162e9ff7596f13f30ba5aeeff6921/src/Logic.hs#L268-L272

If we spell out the `mfilter`, and lift it to the `Action` monad, then we can call `leaveComment` in the branch where the pull request to close is the integration candidate. Something like

```haskell
case Pr.integrationCandidate state of
  Just somePr | somePr == pr -> do
    leaveComment pr "Abandoning this pull request because it was closed."
    pure $ state { Pr.integrationCandidate = Nothing }
  _notTheClosedPr -> pure state
```

To test this, we can do something similar to the [queue position message test](https://github.com/channable/hoff/blob/af1069558d5162e9ff7596f13f30ba5aeeff6921/tests/Spec.hs#L328-L354): feed events to approve a pull request, and then a close event.

**Comment by duijf** [comment]
This was implemented in https://github.com/channable/hoff/pull/57/
