### ISSUE TITLE
No-deploy-Friday nudge

### ISSUE THREAD

**Issue by ruuda** [channable/hoff#56]
@fatho had the idea of requiring a different merge command on Fridays, for example `@bot merge on Friday` instead of just `@bot merge`. It can act as a gentle reminder to not merge risky things on Fridays, while still allowing merges if necessary.

@joris-burgers mentioned that the “Friday” time window should be configurable per repository. Sometimes we want it to include Thursday afternoon as well, for other repositories maybe Friday merges are fine.

We could easily extend the approval check here: https://github.com/channable/hoff/blob/af1069558d5162e9ff7596f13f30ba5aeeff6921/src/Logic.hs#L313-L319

To keep the event loop pure, a `CommentAdded` event should include the instant at which the comment was added. If it was a regular approval, but within the “Friday” window, the bot can leave a comment that explains that it refuses to merge outside this window, with instructions on how to override if you really want to do a merge, similar to how the failed rebase includes instructions on how to do it manually. We should watch out that this instruction comment itself does not trigger the merge. We could make `isReviewer` return false for the bot user (despite it having push access). That would be a good precaution either way.

**Comment by yoricksijsling** [comment]
In all our repositories, we use the `master` branch for two purposes:
* To merge our pull requests to
* To tag and deploy releases

If we would split this into two separate branches (e.g. `stable` and `development`), we would fix this entire problem not just for fridays but for every day of the week!

**Comment by rightfold** [comment]
Scheduling a PR to be merged automatically on Monday would be nice.
