### ISSUE TITLE
Refuse merge if the target branch of a pull request is not the integration branch

### ISSUE THREAD

**Issue by ruuda** [channable/hoff#6]
If you create a pull request against a different branch than the integration branch (master), merging it would merge the entire thing into master. If you are working on a series of dependent PRs, that could create problems. We should bail out on PRs that are created against a different branch than master. We could add better support for dependent PRs later.

**Comment by ruuda** [comment]
Additionally, when the target branch is the integration branch, but other PRs exist that have the current PR branch as target, once we merge it, we could change the base branch of those other PRs.

**Comment by yoricksijsling** [comment]
> We should bail out on PRs that are created against a different branch than master.

It would be great to have this, as a quick solution to prevent accidental closure of a dependent PR.

**Comment by ruuda** [comment]
Note that the PRs with a different base branch than master *are* the dependent PRs. That check would prevent merging the wrong thing. To stop GitHub from closing dependent PRs, we can do #32 and stop deleting branches, and let GitHub delete the branches instead.

**Comment by yoricksijsling** [comment]
Woops right! #32 is the issue I ran into indeed.

**Comment by tomwassenberg** [comment]
> Additionally, when the target branch is the integration branch, but other PRs exist that have the current PR branch as target, once we merge it, we could change the base branch of those other PRs.

GitHub itself is now [retargeting pull requests](https://github.blog/changelog/2020-05-19-pull-request-retargeting/) by the way, which I think is the same as what you were talking about here.

**Comment by ruuda** [comment]
Another idea: instead of refusing the merge, we could take the target branch from the pull request, instead of taking it from the config. Then it would just do what you intended, and it would eliminate one piece of configuration.

**Comment by jochemb** [comment]
Refusing the merge would be a fine solution for this relative edge case. Related question: is github not changing the default name from `master` to `primary` and (how) does that impact this problem?

**Comment by ruuda** [comment]
The branch that Hoff integrates changes into is specified per repository in the configuration: https://github.com/channable/hoff/blob/959aa1e07bd797e888cf4d9ad2ceba6bd615ac63/src/Configuration.hs#L31

At the moment Hoff ignores any data that GitHub exposes about what branch a pull request is targeted at.

I recall seeing something about GitHub changing the default branch name, but when I search for it now, I find [this page](https://github.com/github/renaming), according to which the changes only apply to new repositories, and some features that make changing the default branch smoother. As far as I can tell, no change will be forced onto existing repositories.
