### ISSUE TITLE
Retry when a force-push failed

### ISSUE THREAD

**Issue by ruuda** [channable/hoff#63]
We just observed this in production

```
[Info] executing git -C /var/lib/hoff/checkouts/«redacted» push --force origin b1f075aed05c8eacfcd6a57508162e0074a1a5cf:refs/heads/testing
[Warn] warning: git push --force failed
[Info] Posted comment on 10123: Rebased as b1f075aed05c8eacfcd6a57508162e0074a1a5cf, waiting for CI …
```

Then the authors are waiting indefinitely, but CI never picks up the new commit, because the push failed. Given that GitHub reliability issues have been getting more frequent, this is a case that we have to handle. Probably we can just retry a few times.

**Comment by ruuda** [comment]
We should probably also log this as an error instead of a warning, if it still fails after multiple attempts. It is not a fatal error, but it is something that I would want to be notified about. It would be nice to log errors to Sentry too then :innocent:

**Comment by ruuda** [comment]
@Gijsvs discovered that a second attempt also failed. It might be that the push is explicitly rejected by GitHub, maybe because a file is too large, or maybe because it triggered a credential scan. In that case, we should handle the error and inform the user by leaving a comment.

**Comment by Gijsvs** [comment]
Maybe we can add the `--porcelain` flag to the `git push` so it produces machine readable output to stdout. From it we could parse the `reason` and post that to github in a comment.

https://git-scm.com/docs/git-push#_output

side note: We should not use `--force` but instead use `--force-with-lease`. Going to make PR for this.
