### ISSUE TITLE
Take base branch into account when merging

### ISSUE THREAD

**Issue by p-nilsson** [channable/hoff#65]
I recently used Hoff to merge a PR from branch `foo`, which was based on another branch (`bar`) than `master`. I wanted to first merge the two branches together and then merge it all into master in one go. To my surprise when I tagged Opsbot in the PR from `foo` hoff merged all the changes from both branches into `master` and closed the PR from branch `bar` without merging it.

This was unexpected and I would have preferred to get an error in the original merge if merging two branches of which one is not `master` is not supported instead of having the bot merging stuff that should not yet have gone all the way to `master`.

Is this known behavior?

**Comment by ruuda** [comment]
Yes, this is a known issue: #6. Pull requests would be accepted :innocent:

**Comment by p-nilsson** [comment]
Ahh I will close this in favor of https://github.com/channable/hoff/issues/6 then :ok_hand:
