### ISSUE TITLE
Expose Prometheus metrics for Hoff's state

### ISSUE THREAD

**Issue by bertptrs** [channable/hoff#99]
Currently the only way to gain insight into the state of Hoff is to look at its public status pages. This can be used for debugging but it cannot really provide insight long term. I think it would be nice to have some metrics, in a Prometheus-compatible format, about what Hoff is doing and what it has done.

Some per-project metrics come to mind:

- number of PRs processed (counter)
- number of PRs merged (counter)
- number of PRs failed' (counter)
- queue length
- current build duration (might be more correct to use the starting timestamp of the current build?)

I can think of others which would be fun but not really add value so I've left them out.

I also think it would be useful to have the monitoring endpoint listen on an alternate port from the main HTTP port, so we can separate traffic and firewall things more easily.

**Comment by ReinierMaas** [comment]
@DiegoDiverio I see you merged a PR related to this issue. Did you complete everything that was specified here?

**Comment by DiegoDiverio** [comment]
I split this issue into other issues for the last two metrics of the list:

- https://github.com/channable/hoff/issues/200
- https://github.com/channable/hoff/issues/201

For the pending PR-related metrics, we can reopen an issue, making clear what the behaviour of each metric would be.
